import { CheckCircle2Icon } from 'lucide-react';
import { PageHero } from '../components/ui/PageHero';
import { Reveal } from '../components/ui/Reveal';
import { IMAGES } from '../data/media';

type ProvisionSection = { title: string; body?: string[]; bullets?: string[] };

const SECTIONS: ProvisionSection[] = [
  { title: 'Your Trusted Tour Coordinator', body: ['Founded in 2017, Magical Paradise is an authentic, locally driven Destination Management Company fully licensed by the Sri Lanka Tourism Development Authority (SLTDA).', 'Every tour is planned and operated by our team together with trusted tourism-industry partners. We believe every detail matters in delivering a smooth, safe and memorable experience.'] },
  { title: 'Partial Bookings', body: ['For transport-only, selected-hotel or other partial bookings, our contractual responsibility applies only to the travel components booked through Magical Paradise.', 'We do not hold direct responsibility for independently arranged parts of your holiday. However, you may contact us for guidance if an unexpected difficulty occurs during your stay, and we will gladly assist where reasonably possible.'] },
  { title: 'Hotel and Accommodation Arrangements', body: ['We confirm the agreed tour-package hotels selected by you and provide the relevant details before booking. Clients are encouraged to research each property carefully before confirming arrangements with us.', 'Once reservations have been made, changing hotels on request may not be possible before or during the stay. If a serious, unforeseen situation requires a change, we will assist subject to availability and any additional cost of the new reservation.'] },
  { title: 'Booking Confirmation', body: ['After receiving the required payment, we issue a formal booking validation note. Please check names, dates, services and all other details carefully, and report incomplete or incorrect information to your Magical Paradise representative as soon as possible.'] },
  { title: 'Payment Conditions', bullets: ['Payment can be made by bank transfer or credit card. A service fee may be added to credit-card payments.', 'An initial 50% advance is generally required to confirm the booking. This requirement may be adjusted by our team on a case-by-case basis.', 'The client is responsible for all local and foreign bank-transfer charges. Please instruct your bank accordingly before making payment.', 'Magical Paradise does not add postage fees, booking fees or other hidden charges.'] },
  { title: 'Cancellation by Magical Paradise', body: ['Although we are committed to operating every confirmed journey, we reserve the right to cancel when performance is prevented by force majeure or circumstances beyond the reasonable control of the parties involved.'], bullets: ['Acts of God and natural disasters', 'War, civil commotion, riots or acts of terrorism', 'Strikes or political disturbance', 'Pandemics', 'Failures or events involving third-party suppliers that are beyond our control'] },
  { title: 'Force Majeure and Exceptional Refunds', body: ['In a force-majeure event, Magical Paradise is not liable for death, bodily injury, illness, property damage, direct or indirect financial loss, or failure to perform obligations caused by circumstances outside our control.', 'Where applicable, paid funds will be returned excluding bank charges, or an alternative tour will be offered. We cannot accept responsibility for incidental expenses arising from subsequent arrangements made because of force majeure.'], bullets: ['Unexpected travel advisory issued 30 days or more before the first booking date: a minimum of 90% of the total booking cost will be refunded.', 'Unexpected travel advisory issued within 30 days of the first booking date or during the holiday: all recoverable costs will be refunded.'] },
  { title: 'Cancellation by the Client', body: ['A cancellation must be submitted formally through the agreed communication channel. Charges are calculated according to the date on which Magical Paradise receives the notice and against the total tour price.'], bullets: ['60 days or more before arrival: 100% of the tour-package payment is refunded, less applicable bank service fees.', '30–59 days before arrival: 5% of the invoiced value plus all local and foreign bank charges is retained; the remaining balance is refunded.', 'Less than 30 days before arrival: the invoiced value is non-refundable.', 'Other cancellation refunds are considered case by case. Early checkouts and no-shows are normally non-refundable.', 'For a group cancellation made by the tour leader, each traveller is equally liable for the applicable cancellation cost.'] },
  { title: 'Changes to Confirmed Itineraries', body: ['We make every reasonable effort to operate the original itinerary. A change will be introduced only when unavoidable, communicated in advance whenever possible, and arranged with your convenience in mind.', 'Client change requests are welcome. Additional charges may arise from revised hotels, transport, activities or other services, and these will be communicated before we proceed.'] },
  { title: 'Accuracy of Information Provided by Us', body: ['Magical Paradise takes reasonable care to provide accurate information free from errors and omissions. We cannot be held responsible for information or circumstances that a reasonable travel coordinator could not have been expected to know.', 'Some services depend on third-party providers. Power interruptions, emergency maintenance, seasonal closures, reduced hotel staffing or limited meal arrangements may occasionally occur outside our control.'] },
  { title: 'Information Required from You', body: ['Clients must provide complete and accurate information. Personal information is treated confidentially and used only to arrange and support the booking.', 'The following details are essential to help us provide suitable care and reduce avoidable difficulties during your journey:'], bullets: ['The correct age of every child at the time of travel in Sri Lanka', 'Special health conditions affecting travellers aged over 70', 'Pregnancy, accessibility requirements, wheelchair use or other relevant medical conditions', 'Dietary requirements, vegetarian preferences, food allergies and other restrictions'] },
  { title: 'Customer Care During Your Journey', body: ['Tourism involves a chain of hotels, guides, drivers, venues and activity providers, so rare and unexpected service issues may occur. Our team remains available throughout your stay and will actively work with all parties to resolve concerns with care and minimize disruption to your holiday.'] },
  { title: 'Travel Insurance', body: ['Every traveller must hold valid comprehensive insurance suitable for the type of holiday planned in Sri Lanka.', 'In the event of personal loss, including baggage or valuables, or injury, illness or death, we will provide reasonable guidance. Any claim or legal process must proceed in conjunction with the traveller’s personal insurance policy.'] },
  { title: 'Passport Validity', body: ['Your passport should remain valid for at least six months from the visa-application date. A passport with less than six months of validity may be rejected by the official visa application portal.'] },
];

export function BookingProvisions() {
  return <>
    <PageHero eyebrow="Travel With Confidence" title="Tour Booking Contractual Provisions" subtitle="Magical Paradise booking requirements, responsibilities, payment conditions, cancellation terms and important travel information." image={IMAGES.galle} imageAlt="Sri Lankan coastline and Galle Fort" locationTag="Magical Paradise" />
    <section className="bg-sand py-16"><div className="mx-auto max-w-4xl px-6 text-center"><Reveal><p className="font-serif text-2xl font-light leading-relaxed text-jungle sm:text-3xl">Please read these provisions carefully before confirming your arrangements. They explain the responsibilities shared by Magical Paradise, our travel partners and every guest.</p></Reveal></div></section>
    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-4xl space-y-6 px-6">{SECTIONS.map((section, index) => <Reveal key={section.title} delay={(index % 2) * .04}><article className="rounded-xl border border-jungle/10 bg-white p-7 shadow-card sm:p-9"><p className="text-xs font-semibold uppercase tracking-[.16em] text-gold-dark">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-2 font-serif text-2xl text-jungle sm:text-3xl">{section.title}</h2>{section.body && <div className="mt-4 space-y-3 text-sm leading-7 text-jungle-muted">{section.body.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div>}{section.bullets && <ul className="mt-5 space-y-3">{section.bullets.map(item => <li key={item} className="flex gap-3 text-sm leading-7 text-jungle-muted"><CheckCircle2Icon className="mt-1.5 h-4 w-4 shrink-0 text-gold-dark" strokeWidth={1.7}/><span>{item}</span></li>)}</ul>}</article></Reveal>)}</div></section>
  </>;
}
