import { PageHero } from '../components/ui/PageHero';
import { Reveal } from '../components/ui/Reveal';
import { IMAGES } from '../data/media';

const SECTIONS = [
  { title: 'Your Trusted Tour Coordinator', body: ['Founded in 2017, Magical Paradise is an authentic, locally driven Destination Management Company fully licensed by the Sri Lanka Tourism Development Authority (SLTDA). Every arrangement is meticulously planned and operated by us together with trusted tourism partners.'] },
  { title: 'Partial Bookings', body: ['For transport-only, selected-hotel or other partial bookings, our responsibility applies to the components booked through us. We remain available to offer guidance and support should unexpected difficulties arise elsewhere in your holiday.'] },
  { title: 'Hotel & Accommodation Arrangements', body: ['We guarantee the agreed hotels selected by the client and share package details before confirmation. Please research hotels before confirming. Changes after reservation or during the stay are normally unavailable; where an unforeseen serious need arises, we will assist subject to availability and additional costs.'] },
  { title: 'Booking Confirmation', body: ['After receiving payment, we issue a formal validation note. Clients must verify all details and report incomplete or incorrect information to our representative as soon as possible.'] },
  { title: 'Payments', body: ['Payment may be made by bank transfer or credit card; card service fees may apply.', 'A 50% advance is generally required to confirm a booking, subject to case-by-case discretion.', 'Clients bear all local and foreign bank-transfer charges. There are no additional postage, booking or hidden charges.'] },
  { title: 'Cancellation by Magical Paradise', body: ['We may cancel where performance is prevented by force majeure, including natural disasters, war, civil commotion, terrorism, strikes, political disturbance, pandemics or third-party events beyond our control.', 'Where applicable, funds will be returned excluding bank charges, or an alternative tour offered. We are not liable for incidental expenses arising from subsequent force-majeure arrangements.', 'For an unexpected travel advisory: 30 days or more before the first booking, a minimum 90% of total booking cost is refunded; within 30 days or during travel, all recoverable costs are refunded.'] },
  { title: 'Cancellation by the Client', body: ['60 days or more before arrival: 100% refund less bank service fees.', '30–59 days before arrival: 5% of invoiced value plus local and foreign bank charges; the balance is refunded.', 'Less than 30 days before arrival: non-refundable.', 'Other refunds are assessed case by case. Early checkouts and no-shows are normally non-refundable. For group cancellation by a tour leader, each individual is equally liable for cancellation costs.'] },
  { title: 'Changes to Confirmed Itineraries', body: ['We make every effort to operate the original itinerary. Unavoidable changes will be communicated in advance and handled with your convenience in mind.', 'Client change requests are welcome; any resulting additional costs will be communicated before proceeding.'] },
  { title: 'Information, Health & Special Requirements', body: ['We take reasonable care to ensure our information is accurate, while some services remain dependent on third-party providers and circumstances outside our control.', 'Clients must provide accurate information. Please disclose children’s ages at travel, health conditions for guests over 70, pregnancy, accessibility or wheelchair needs, medical conditions, dietary restrictions and allergies. Information is treated confidentially and used for tour arrangements.'] },
  { title: 'Customer Care, Insurance & Passports', body: ['Our team remains available throughout your stay and will work actively to resolve unexpected service issues with care.', 'Every traveler must hold comprehensive insurance appropriate to the planned holiday. Personal loss, injury, illness or death are handled in conjunction with the traveler’s insurance policy.', 'Passports should have at least six months’ validity from the visa application date; shorter validity may result in visa rejection.'] },
];

export function BookingProvisions() { return <><PageHero eyebrow="Travel With Confidence" title="Tour Booking Contractual Provisions" subtitle="Magical Paradise booking requisites, responsibilities, payment conditions and important travel information." image={IMAGES.galle} imageAlt="Sri Lankan coastline and Galle Fort"/><section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-4xl space-y-6 px-6">{SECTIONS.map((section,i)=><Reveal key={section.title} delay={(i%2)*.04}><article className="rounded-lg border border-jungle/10 bg-white p-7 shadow-card sm:p-9"><p className="text-xs font-semibold uppercase tracking-[.16em] text-gold-dark">{String(i+1).padStart(2,'0')}</p><h2 className="mt-2 font-serif text-2xl text-jungle sm:text-3xl">{section.title}</h2><div className="mt-4 space-y-3 text-sm leading-7 text-jungle-muted">{section.body.map(p=><p key={p}>{p}</p>)}</div></article></Reveal>)}</div></section></>; }
