import React from 'react';
import { SparklesIcon } from 'lucide-react';
import { PageHero } from '../components/ui/PageHero';
import { Reveal } from '../components/ui/Reveal';
import { SectionHeading } from '../components/ui/SectionHeading';
import { CtaStrip } from '../components/sections/CtaStrip';
import { FOUR_CS, GEMSTONES, type Gemstone } from '../data/gemstones';
import { IMAGES } from '../data/media';

const sapphire = GEMSTONES.find(stone => stone.slug === 'sapphire')!;

export function CeylonGems(){return <>
  <PageHero eyebrow="Island of Gems" title="Ceylon Gems" subtitle="Discover Sri Lanka’s extraordinary gemstone heritage — from celebrated Ceylon sapphires and rare cat’s eyes to moonstones, spinels and centuries-old gem traditions." image={IMAGES.galle} imageAlt="Sri Lankan heritage setting introducing the story of Ceylon gems"/>

  <section className="bg-ivory py-20 lg:py-24"><div className="mx-auto max-w-content px-6"><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr] lg:gap-16"><GemVisual stone={GEMSTONES[0]}/><Reveal><p className="eyebrow text-gold-dark">A 2,500-Year Heritage</p><h2 className="mt-4 font-serif text-3xl font-light text-jungle sm:text-4xl">Sri Lanka — The Island of Gems</h2><p className="mt-6 text-[15px] leading-8 text-jungle-muted">For more than 2,500 years, Sri Lanka has been celebrated for gemstones of exceptional beauty. The island is known globally for high-quality stones—particularly sapphires—and its gem traditions remain closely connected to local culture, inherited knowledge and heritage.</p></Reveal></div></div></section>

  <section id="sapphire" className="scroll-mt-24 bg-jungle-deep py-20 lg:py-24"><div className="mx-auto grid max-w-content items-center gap-12 px-6 lg:grid-cols-2 lg:gap-16"><div><p className="eyebrow text-gold-light">The Ceylon Signature</p><h2 className="mt-4 font-serif text-4xl font-light text-ivory">Ceylon Sapphire</h2><p className="mt-6 text-[15px] leading-8 text-ivory/70">{sapphire.description}</p><div className="mt-7 flex flex-wrap gap-2">{sapphire.varieties?.map(item=><span key={item} className="rounded-full border border-gold/30 px-4 py-2 text-xs text-gold-light">{item}</span>)}</div><p className="mt-8 text-xs uppercase tracking-[.14em] text-ivory/45">Sapphire colors</p><p className="mt-3 text-sm leading-7 text-ivory/70">{sapphire.colors?.join(' · ')}</p></div><GemVisual stone={sapphire} dark/></div></section>

  <section className="bg-sand py-20 lg:py-24"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Gemstone Discovery" title="Explore Sri Lankan Gemstones" subtitle="An introduction to the principal gemstone families and varieties described in Sri Lanka’s gem tradition."/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{GEMSTONES.map((stone,index)=><Reveal key={stone.slug} delay={index%3*.05} className="h-full"><a href={`#${stone.slug}`} className="group flex h-full flex-col overflow-hidden rounded-lg border border-jungle/10 bg-white shadow-card"><GemVisual stone={stone} compact/><div className="flex flex-1 flex-col p-6"><h3 className="font-serif text-2xl text-jungle">{stone.name}</h3><p className="mt-3 text-sm leading-6 text-jungle-muted">{stone.shortDescription}</p><div className="mt-4 flex flex-wrap gap-1.5">{[...(stone.varieties??[]),...(stone.colors??[])].slice(0,3).map(tag=><span key={tag} className="rounded-full bg-sand px-2.5 py-1 text-[10px] text-jungle-muted">{tag}</span>)}</div><span className="mt-auto pt-5 text-[11px] font-medium uppercase tracking-[.14em] text-gold-dark group-hover:text-jungle">Learn More ↓</span></div></a></Reveal>)}</div></div></section>

  <section className="bg-ivory py-20 lg:py-24"><div className="mx-auto max-w-content space-y-8 px-6">{GEMSTONES.filter(stone=>stone.slug!=='sapphire').map((stone,index)=><Reveal key={stone.slug}><article id={stone.slug} className="scroll-mt-24 grid overflow-hidden rounded-lg border border-jungle/10 bg-white lg:grid-cols-[.75fr_1.25fr]"><GemVisual stone={stone}/><div className="flex flex-col justify-center p-8 sm:p-10 lg:p-12"><p className="eyebrow text-gold-dark">Gemstone {String(index+1).padStart(2,'0')}</p><h2 className="mt-3 font-serif text-3xl font-light text-jungle">{stone.name}</h2><p className="mt-5 text-[15px] leading-8 text-jungle-muted">{stone.description}</p>{stone.varieties?.length?<TagGroup title="Varieties" items={stone.varieties}/>:null}{stone.colors?.length?<TagGroup title="Colors" items={stone.colors}/>:null}{stone.highlights?.length?<TagGroup title="Notable Details" items={stone.highlights}/>:null}</div></article></Reveal>)}</div></section>

  <section className="bg-sand py-20 lg:py-24"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="A Practical Guide" title="How to Buy Quality Gemstones" subtitle="Understanding the Four C’s helps you assess a coloured gemstone as a complete object rather than judging any single quality in isolation."/><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{FOUR_CS.map((item,index)=><Reveal key={item.title} delay={index*.06} className="h-full"><article className="h-full rounded-lg border border-jungle/10 bg-white p-7 shadow-card"><span className="font-serif text-2xl text-gold-dark">0{index+1}</span><h2 className="mt-4 font-serif text-2xl text-jungle">{item.title}</h2><p className="mt-3 text-sm leading-6 text-jungle-muted">{item.description}</p><h3 className="mt-6 text-[10px] font-medium uppercase tracking-[.14em] text-jungle">Buying Tips</h3><ul className="mt-3 space-y-2">{item.tips.map(tip=><li key={tip} className="flex gap-2 text-xs leading-5 text-jungle-muted"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-gold"/>{tip}</li>)}</ul></article></Reveal>)}</div></div></section>

  <CtaStrip eyebrow="Discover More" title="Explore the story behind Sri Lanka’s gems" description="Let our travel specialists connect your journey with authentic cultural, artisan and gemstone experiences across Sri Lanka." primaryLabel="Start Planning" primaryTo="/plan-your-trip"/>
  </>}

function GemVisual({stone,dark=false,compact=false}:{stone:Gemstone;dark?:boolean;compact?:boolean}){if(stone.image)return <img src={stone.image} alt={stone.imageAlt} loading="lazy" className={`${compact?'aspect-[16/10]':'min-h-64 h-full'} w-full object-cover`}/>;return <div role="img" aria-label={`${stone.imageAlt} image placeholder`} className={`${compact?'aspect-[16/10]':'min-h-64 h-full'} flex w-full items-center justify-center ${dark?'border border-white/10 bg-white/5':'bg-sand'}`}><div className="text-center"><span className={`mx-auto flex h-16 w-16 items-center justify-center rounded-full ${dark?'bg-white/10 text-gold-light':'bg-white text-gold-dark'}`}><SparklesIcon className="h-7 w-7" strokeWidth={1.25}/></span><p className={`mt-4 text-xs uppercase tracking-[.16em] ${dark?'text-ivory/50':'text-jungle-muted'}`}>{stone.name}</p></div></div>}
function TagGroup({title,items}:{title:string;items:string[]}){return <div className="mt-6"><h3 className="text-[10px] font-medium uppercase tracking-[.14em] text-jungle-muted">{title}</h3><div className="mt-3 flex flex-wrap gap-2">{items.map(item=><span key={item} className="rounded-full bg-sand px-3 py-1.5 text-xs text-jungle">{item}</span>)}</div></div>}
