'use client';
import React,{useState} from 'react';
import { PageHero } from '../components/ui/PageHero';
import { DayTourCard } from '../components/cards/DayTourCard';
import { Reveal } from '../components/ui/Reveal';
import { SectionHeading } from '../components/ui/SectionHeading';
import { CtaStrip } from '../components/sections/CtaStrip';
import { DAY_TOURS,DAY_TOUR_CATEGORIES,STAY_BASED_TOURS } from '../data/dayTours';
import { IMAGES } from '../data/media';

export function DayTours(){const[filter,setFilter]=useState('all');const categories=filter==='all'?DAY_TOUR_CATEGORIES:DAY_TOUR_CATEGORIES.filter(x=>x.id===filter);return <>
  <PageHero eyebrow="Discover More in a Day" title="Day Tours in Sri Lanka" subtitle="From wildlife safaris and ancient kingdoms to coastal escapes, scenic flights and local city experiences, discover Sri Lanka through carefully curated day journeys." image={IMAGES.ella} imageAlt="A scenic Sri Lankan day journey through the hill country" stats={[{value:`${DAY_TOURS.length}+`,label:'Day Tours'},{value:'8',label:'Categories'},{value:'1',label:'Unforgettable Day'}]}/>
  <section className="sticky top-[73px] z-30 border-b border-jungle/10 bg-ivory/95 backdrop-blur-md"><div className="mx-auto max-w-content px-6"><div className="no-scrollbar flex gap-2 overflow-x-auto py-4">{[['all','All'],...DAY_TOUR_CATEGORIES.map(x=>[x.id,x.title.replace(' Day Tours','').replace(' – Day Tours','')])].map(([id,label])=><button key={id} type="button" onClick={()=>setFilter(id)} aria-pressed={filter===id} className={`shrink-0 rounded-full px-5 py-2.5 text-[10px] font-medium uppercase tracking-[.12em] transition-colors ${filter===id?'bg-jungle text-ivory':'text-jungle-muted hover:bg-sand hover:text-jungle'}`}>{label}</button>)}</div></div></section>
  {categories.map((category,index)=>{const tours=DAY_TOURS.filter(t=>t.category===category.id);return <section id={category.id} key={category.id} className={`${index%2?'bg-sand':'bg-ivory'} scroll-mt-40 py-16 lg:py-20`}><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow={`Collection ${String(index+1).padStart(2,'0')}`} title={category.title} subtitle={category.description}/><ul className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{tours.map((tour,i)=><li key={tour.slug}><Reveal delay={i%3*.05} className="h-full"><DayTourCard tour={tour}/></Reveal></li>)}</ul></div></section>})}
  {(filter==='all')?<section className="bg-jungle-deep py-20 lg:py-24"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Start Where You Stay" title="Explore Day Tours From Your Stay" subtitle="Quickly discover popular day journeys suited to your current base." tone="light"/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{STAY_BASED_TOURS.map((group,index)=><Reveal key={group.title} delay={index*.05} className="h-full"><article className="h-full rounded-lg border border-white/10 bg-white/5 p-6"><h3 className="font-serif text-xl text-ivory">{group.title}</h3><ul className="mt-4 space-y-2">{group.items.map(item=><li key={item} className="text-sm text-ivory/65">{item}</li>)}</ul></article></Reveal>)}</div></div></section>:null}
  <section className="bg-ivory py-8"><p className="mx-auto max-w-content px-6 text-center text-xs text-jungle-muted">Travel times are approximate and may vary depending on traffic, weather and road conditions.</p></section>
  <CtaStrip eyebrow="Make the Most of Your Day" title="Turn one day into an unforgettable journey" description="Tell us where you are staying and what you would love to experience, and our travel specialists will shape the right day tour for you." primaryLabel="Plan Your Day Tour" primaryTo="/plan-your-trip"/>
  </>}
