import React from 'react';
import Link from 'next/link';
import { ArrowLeftIcon, CalendarIcon, ClockIcon, MapPinIcon } from 'lucide-react';
import { PageHero } from '../components/ui/PageHero';
import { DayTourCard } from '../components/cards/DayTourCard';
import { Reveal } from '../components/ui/Reveal';
import { CtaStrip } from '../components/sections/CtaStrip';
import { DAY_TOURS,type DayTour } from '../data/dayTours';

export function DayTourDetail({tour}:{tour:DayTour}){const related=DAY_TOURS.filter(x=>x.slug!==tour.slug&&x.category===tour.category).slice(0,3);return <>
  <PageHero eyebrow={tour.category} title={tour.title} subtitle={tour.shortDescription} image={tour.image} imageAlt={`${tour.title} in Sri Lanka`}/>
  <section className="bg-ivory py-16 lg:py-20"><div className="mx-auto max-w-content px-6"><Link href="/day-tours" className="inline-flex items-center gap-2 text-[11px] font-medium uppercase tracking-[.16em] text-jungle-muted hover:text-jungle"><ArrowLeftIcon className="h-3.5 w-3.5"/>Back to Day Tours</Link><div className="mt-10 grid gap-12 lg:grid-cols-[1.6fr_1fr] lg:gap-16"><div>
    <Reveal><p className="eyebrow text-gold-dark">Tour Introduction</p><h2 className="mt-3 font-serif text-3xl font-light text-jungle">Make the most of your day</h2><p className="mt-5 text-[15px] leading-8 text-jungle-muted">{tour.description}</p></Reveal>
    {tour.thingsToDo?.length?<InfoList eyebrow="Your Experience" title="Things You Will Do" items={tour.thingsToDo}/>:null}
    {tour.nearbyExperiences?.length?<InfoList eyebrow="Continue Exploring" title="Nearby Experiences" items={tour.nearbyExperiences}/>:null}
    {tour.notes?.length?<InfoList eyebrow="Before You Go" title="Things You Should Know" items={tour.notes}/>:null}
  </div><aside className="lg:sticky lg:top-28 lg:self-start"><div className="rounded-lg border border-jungle/10 bg-white p-7 shadow-card"><h2 className="font-serif text-xl text-jungle">Tour Information</h2><dl className="mt-5 space-y-5">{tour.travelDuration?.map(value=><div key={value} className="flex gap-3"><ClockIcon className="mt-0.5 h-4 w-4 shrink-0 text-gold-dark"/><div><dt className="text-[10px] uppercase tracking-[.16em] text-jungle-muted">Travel Duration</dt><dd className="mt-1 text-sm text-jungle">{value}</dd></div></div>)}{tour.whenToGo?<div className="flex gap-3"><CalendarIcon className="mt-0.5 h-4 w-4 shrink-0 text-gold-dark"/><div><dt className="text-[10px] uppercase tracking-[.16em] text-jungle-muted">When to Go</dt><dd className="mt-1 text-sm text-jungle">{tour.whenToGo}</dd></div></div>:null}{tour.departureAreas?.length?<div className="flex gap-3"><MapPinIcon className="mt-0.5 h-4 w-4 shrink-0 text-gold-dark"/><div><dt className="text-[10px] uppercase tracking-[.16em] text-jungle-muted">Available From</dt><dd className="mt-1 text-sm text-jungle">{tour.departureAreas.join(' · ')}</dd></div></div>:null}</dl><p className="mt-6 border-t border-jungle/10 pt-5 text-xs leading-5 text-jungle-muted">Travel times are approximate and may vary depending on traffic, weather and road conditions.</p><Link href="/plan-your-trip" className="mt-6 inline-flex w-full justify-center rounded-full bg-jungle px-6 py-3.5 text-[11px] uppercase tracking-[.16em] text-ivory hover:bg-jungle-light">Plan This Day Tour</Link></div></aside></div></div></section>
  {related.length?<section className="bg-sand py-16 lg:py-20"><div className="mx-auto max-w-content px-6"><h2 className="font-serif text-3xl font-light text-jungle">Related Day Tours</h2><ul className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{related.map(x=><li key={x.slug}><DayTourCard tour={x}/></li>)}</ul></div></section>:null}
  <CtaStrip eyebrow="Make the Most of Your Day" title="Turn one day into an unforgettable journey" description="Tell us where you are staying and what you would love to experience, and our travel specialists will shape the right day tour for you." primaryLabel="Plan Your Day Tour" primaryTo="/plan-your-trip"/>
  </>}

function InfoList({eyebrow,title,items}:{eyebrow:string;title:string;items:string[]}){return <Reveal className="mt-12"><p className="eyebrow text-gold-dark">{eyebrow}</p><h2 className="mt-3 font-serif text-3xl font-light text-jungle">{title}</h2><ul className="mt-6 grid gap-3 sm:grid-cols-2">{items.map(item=><li key={item} className="flex gap-3 rounded-lg border border-jungle/10 bg-white p-4 text-sm leading-6 text-jungle-muted"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-gold"/>{item}</li>)}</ul></Reveal>}
