import Link from 'next/link';
import { AlertTriangleIcon, CameraIcon, CheckIcon, ExternalLinkIcon, EyeIcon, FileCheckIcon, GaugeIcon, MapIcon, MoonIcon, PlaneIcon, RadioIcon, ShieldCheckIcon, UserCheckIcon, WindIcon } from 'lucide-react';
import { PageHero } from '../components/ui/PageHero';
import { Reveal } from '../components/ui/Reveal';
import { SectionHeading } from '../components/ui/SectionHeading';
import { IMAGES } from '../data/media';
import { SITE } from '../data/site';

const steps = [
  { n: '01', title: 'Check the Zone Map', text: 'Review your exact flight location for restricted, authorization, altitude-limit and warning zones.' },
  { n: '02', title: 'Register When Required', text: 'Confirm whether the aircraft and operator must be registered under the current CAASL category rules.' },
  { n: '03', title: 'Apply for Approval', text: 'Submit pilot, aircraft, purpose, location and supporting documents through the CAASL Drone Portal.' },
  { n: '04', title: 'Carry Your Documents', text: 'Keep registration, approval, insurance and any local clearances available throughout the operation.' },
];

const rules = [
  { icon: EyeIcon, title: 'Keep Visual Line of Sight', text: 'The remote pilot must maintain VLOS and remain aware of people, aircraft, obstacles and the surrounding environment.' },
  { icon: GaugeIcon, title: 'Respect Height & Speed Limits', text: 'The current general maximum altitude is 400 ft (120 m) above ground level. Follow any lower zone-specific limit and applicable speed restriction.' },
  { icon: PlaneIcon, title: 'Give Way to Manned Aircraft', text: 'Always give way to manned aircraft and never operate in controlled airspace or near an airport without the required authorization.' },
  { icon: WindIcon, title: 'Fly Only in Safe Weather', text: 'Do not fly in inclement weather or poor visibility. Confirm that conditions remain safe for the entire planned operation.' },
  { icon: MoonIcon, title: 'Night Operations Are Restricted', text: 'Do not conduct night operations unless the specific approval and operating conditions required by CAASL have been obtained.' },
  { icon: UserCheckIcon, title: 'One Pilot, One Drone', text: 'A remote pilot should operate only one aircraft at a time and must not launch or control it from a moving vehicle, boat or platform.' },
  { icon: ShieldCheckIcon, title: 'Protect People & Property', text: 'Stay clear of people, birds, buildings and property, and respect privacy, environmental and local site restrictions.' },
  { icon: CameraIcon, title: 'Camera Drones Need Care', text: 'Data-capturing sensors can trigger registration, security and local authorization requirements regardless of the aircraft’s size.' },
];

const insurance = [
  ['A', '0.25 kg or below', 'Not required'],
  ['B', 'Above 0.25–0.9 kg', 'LKR 100,000'],
  ['C', 'Above 0.9–4 kg', 'LKR 400,000'],
  ['D', 'Above 4–15 kg', 'LKR 1,500,000'],
  ['—', 'Above 15–25 kg', 'LKR 2,500,000'],
  ['F', 'Above 25 kg', 'LKR 2,500,000 + LKR 100,000 per additional kg'],
];

const LinkButton = ({ href, children, light = false }: { href: string; children: React.ReactNode; light?: boolean }) => <a href={href} target="_blank" rel="noreferrer noopener" className={light ? 'inline-flex items-center gap-2 rounded-full border border-ivory/30 px-6 py-3 text-[11px] font-medium uppercase tracking-[.14em] text-ivory transition hover:bg-ivory hover:text-jungle' : 'inline-flex items-center gap-2 rounded-full bg-jungle px-6 py-3 text-[11px] font-semibold uppercase tracking-[.14em] text-ivory transition hover:bg-jungle-deep'}>{children}<ExternalLinkIcon className="h-3.5 w-3.5"/></a>;

export function DroneRegulations() {
  return <>
    <PageHero eyebrow="Sri Lanka Travel Guide" title="Drone Regulations" subtitle="Plan responsible aerial photography in Sri Lanka with the right registration, approvals and operating precautions." image={IMAGES.sigiriya} imageAlt="Sigiriya Rock Fortress rising above the Sri Lankan landscape" locationTag="Fly Responsibly" stats={[{ value: '400 ft', label: 'General Max Altitude' }, { value: 'VLOS', label: 'Required' }, { value: 'CAASL', label: 'Regulator' }]}>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#before-you-fly" className="rounded-full bg-gold px-8 py-4 text-xs font-semibold uppercase tracking-[.16em] text-jungle-deep">Before You Fly</a><a href="https://portal.caa.lk/drone/" target="_blank" rel="noreferrer noopener" className="rounded-full border border-ivory/35 bg-white/10 px-8 py-4 text-xs font-medium uppercase tracking-[.16em] text-ivory">CAASL Drone Portal</a></div>
    </PageHero>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto grid max-w-content gap-12 px-6 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><Reveal><div><p className="eyebrow text-gold-dark">Regulated Airspace</p><h2 className="mt-4 font-serif text-4xl font-light leading-tight text-jungle sm:text-5xl">Flying a drone in Sri Lanka</h2></div></Reveal><Reveal delay={.08}><div className="space-y-5 text-[15px] leading-8 text-jungle-muted sm:text-base"><p>Drone operations in Sri Lanka are regulated by the Civil Aviation Authority of Sri Lanka (CAASL). Registration alone does not automatically authorize a flight: the location, aircraft, purpose and onboard sensors can introduce additional approval requirements.</p><p>Rules and geographical zones can change. Always check the official CAASL Drone Portal and zone map shortly before applying and again before flying.</p><div className="flex flex-wrap gap-3 pt-3"><LinkButton href="https://portal.caa.lk/drone/">Official Drone Portal</LinkButton><LinkButton href="https://portal.caa.lk/drone/map.html">Check Zone Map</LinkButton></div></div></Reveal></div></section>

    <section id="before-you-fly" className="scroll-mt-24 bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Approval Journey" title="Before You Fly" subtitle="Use the official portal for the latest forms, categories, processing requirements and geographical restrictions."/><ol className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{steps.map((x,i)=><li key={x.n}><Reveal delay={i*.05} className="h-full"><div className="h-full rounded-xl border border-jungle/10 bg-ivory p-7"><span className="font-serif text-4xl text-gold">{x.n}</span><h3 className="mt-5 font-serif text-xl text-jungle">{x.title}</h3><p className="mt-3 text-sm leading-7 text-jungle-muted">{x.text}</p></div></Reveal></li>)}</ol></div></section>

    <section className="bg-jungle py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Registration" title="Know Your Aircraft Category" subtitle="The current framework uses C0, C1, C2, C3, C4 and C25+ classifications, with requirements based on aircraft type, mass, construction and onboard sensors." tone="light"/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Reveal><div className="h-full rounded-xl border border-ivory/15 p-7"><RadioIcon className="h-7 w-7 text-gold-light"/><h3 className="mt-5 font-serif text-2xl text-ivory">Categories C1, C2, C3 & C25+</h3><p className="mt-4 text-sm leading-7 text-ivory/70">UAS in these categories, excluding model aircraft and toys, must be registered with CAASL and carry the required identification.</p></div></Reveal><Reveal delay={.05}><div className="h-full rounded-xl border border-ivory/15 p-7"><CameraIcon className="h-7 w-7 text-gold-light"/><h3 className="mt-5 font-serif text-2xl text-ivory">C0 & C4 with Sensors</h3><p className="mt-4 text-sm leading-7 text-ivory/70">Aircraft fitted with a camera or other data-capturing sensor can require CAASL registration even when their mass category would otherwise be lighter.</p></div></Reveal><Reveal delay={.1}><div className="h-full rounded-xl border border-ivory/15 p-7"><FileCheckIcon className="h-7 w-7 text-gold-light"/><h3 className="mt-5 font-serif text-2xl text-ivory">Privately Built Drones</h3><p className="mt-4 text-sm leading-7 text-ivory/70">Registration requirements depend on weight, sensors and whether a serial number is present. Use the current CAASL forms listed on the approval page.</p></div></Reveal></div><p className="mx-auto mt-9 max-w-3xl text-center text-xs leading-6 text-ivory/60">Registration is generally valid for five years and proof of registration should be available whenever the aircraft is operated. Confirm the exact category using the latest implementing standard.</p></div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Core Operating Rules" title="Fly Safely & Legally"/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{rules.map((x,i)=><Reveal key={x.title} delay={(i%4)*.04}><article className="h-full rounded-xl border border-jungle/10 bg-white p-7 shadow-card"><x.icon className="h-7 w-7 text-gold-dark" strokeWidth={1.5}/><h3 className="mt-5 font-serif text-xl text-jungle">{x.title}</h3><p className="mt-3 text-sm leading-7 text-jungle-muted">{x.text}</p></article></Reveal>)}</div></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Location Matters" title="Restricted & Sensitive Areas" subtitle="A beautiful viewpoint is not automatically an approved launch site."/><div className="mt-12 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Reveal><article className="rounded-xl border border-jungle/10 bg-ivory p-8 sm:p-10"><MapIcon className="h-8 w-8 text-gold-dark"/><h3 className="mt-6 font-serif text-3xl text-jungle">Check every planned location</h3><p className="mt-5 text-sm leading-7 text-jungle-muted">The CAASL map identifies no-fly, authorization, warning and altitude-controlled zones, including areas near airports and air bases. Archaeological sites, sanctuaries, heritage locations, private property and other designated sites may also require permission from the relevant local authority.</p><div className="mt-7"><LinkButton href="https://portal.caa.lk/drone/map.html">Open Drone Zone Map</LinkButton></div></article></Reveal><Reveal delay={.06}><article className="h-full rounded-xl bg-jungle-deep p-8 text-ivory sm:p-10"><AlertTriangleIcon className="h-8 w-8 text-gold-light"/><h3 className="mt-6 font-serif text-3xl">Do not assume clearance</h3><ul className="mt-6 space-y-4 text-sm leading-7 text-ivory/70">{['Airport, defence and controlled-airspace restrictions apply.', 'Territorial-water operations require authorization.', 'Property-owner consent does not replace aviation approval.', 'Security or site clearance does not replace CAASL flight approval.', 'Commercial work requires the appropriate special authorization.'].map(x=><li key={x} className="flex gap-3"><CheckIcon className="mt-1 h-4 w-4 shrink-0 text-gold-light"/>{x}</li>)}</ul></article></Reveal></div></div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Third-Party Protection" title="Minimum Insurance Cover" subtitle="CAASL publishes minimum third-party liability cover by maximum take-off weight. Verify the current requirement before operating."/><div className="mt-12 overflow-hidden rounded-xl border border-jungle/10 bg-white shadow-card"><div className="grid grid-cols-[.45fr_1fr_1.3fr] bg-jungle px-5 py-4 text-[10px] font-semibold uppercase tracking-[.12em] text-ivory sm:px-7"><span>Category</span><span>MTOM</span><span>Minimum Cover</span></div>{insurance.map((row,i)=><div key={row.join('')} className={`grid grid-cols-[.45fr_1fr_1.3fr] gap-3 px-5 py-4 text-xs leading-5 sm:px-7 sm:text-sm ${i%2 ? 'bg-sand/60' : 'bg-white'}`}><span className="font-semibold text-jungle">{row[0]}</span><span className="text-jungle-muted">{row[1]}</span><span className="text-jungle">{row[2]}</span></div>)}</div></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Visitors & Professionals" title="Special Situations"/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Reveal><article className="h-full rounded-xl border border-jungle/10 bg-ivory p-8"><h3 className="font-serif text-2xl text-jungle">Bringing a Drone to Sri Lanka</h3><p className="mt-4 text-sm leading-7 text-jungle-muted">Importing a drone can require clearances from CAASL, the Ministry of Defence, TRCSL and the Import & Export Control Department. Check the approved drone-type list and complete the import process before travelling.</p></article></Reveal><Reveal delay={.05}><article className="h-full rounded-xl border border-jungle/10 bg-ivory p-8"><h3 className="font-serif text-2xl text-jungle">Foreign Visitors</h3><p className="mt-4 text-sm leading-7 text-jungle-muted">A drone brought for a holiday may require temporary registration and operational approval. Heritage sites, sanctuaries and other designated locations can require separate local clearance.</p></article></Reveal><Reveal delay={.1}><article className="h-full rounded-xl border border-jungle/10 bg-ivory p-8"><h3 className="font-serif text-2xl text-jungle">Commercial Operations</h3><p className="mt-4 text-sm leading-7 text-jungle-muted">Commercial filming and other professional operations require the appropriate authorization from the Director General of Civil Aviation, regardless of aircraft size.</p></article></Reveal></div></div></section>

    <section className="bg-jungle-deep py-20 lg:py-24"><div className="mx-auto max-w-4xl px-6 text-center"><Reveal><p className="eyebrow text-gold-light">Official Guidance First</p><h2 className="mt-4 font-serif text-4xl text-ivory sm:text-5xl">Confirm the rules before every flight</h2><p className="mx-auto mt-6 max-w-2xl text-[15px] leading-8 text-ivory/70">Regulations, forms and geographical zones can change. Use CAASL’s official portal as the final authority for registration, approval and operating conditions.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><LinkButton href="https://portal.caa.lk/drone/" light>CAASL Drone Portal</LinkButton><LinkButton href="https://www.caa.lk/en/licenses-certificates-approvals/approvals/drone-approvals" light>Drone Regulations</LinkButton><a href={SITE.whatsapp} target="_blank" rel="noreferrer noopener" className="rounded-full bg-gold px-6 py-3 text-[11px] font-semibold uppercase tracking-[.14em] text-jungle-deep">Ask Our Team</a></div><p className="mt-8 text-xs text-ivory/45">CAASL Drone Operations · +94 11 235 8819 · drone@caa.lk</p></Reveal></div></section>
  </>;
}
