import React from 'react';
import {PageHero} from '../components/ui/PageHero';
import {Reveal} from '../components/ui/Reveal';
import {SectionHeading} from '../components/ui/SectionHeading';
import {CtaStrip} from '../components/sections/CtaStrip';
import {GroupTourInquiryForm} from '../components/forms/GroupTourInquiryForm';
import {IMAGES} from '../data/media';

const EXPERIENCES=[{title:'Luxury Beach Escapes',text:'Celebrate along Sri Lanka’s golden coastline.',image:IMAGES.mirissa},{title:'Misty Hill-Country Retreats',text:'Gather in cool highlands and colonial-style surroundings.',image:IMAGES.teaCountry},{title:'Private Villa Gatherings',text:'Create space for connection in a private setting.',image:IMAGES.hotel},{title:'Wildlife Adventures',text:'Share memorable encounters in Sri Lanka’s wilderness.',image:IMAGES.yala},{title:'Maldives Extensions',text:'Continue with a luxury island escape beyond Sri Lanka.',image:IMAGES.maldives},{title:'Tailor-Made Family Journeys',text:'Travel together through the island’s most scenic destinations.',image:IMAGES.sigiriya}];
export function FamilyEscapes(){return <>
  <PageHero eyebrow="Celebrate Together" title="Family Escapes & Private Celebrations" subtitle="Celebrate life’s most meaningful moments through thoughtfully curated journeys across Sri Lanka and beyond." image={IMAGES.mirissa} imageAlt="A private family celebration on Sri Lanka's coast"/>
  <section className="bg-ivory py-20 lg:py-24"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Made for Your People" title="Meaningful journeys, beautifully shared" subtitle="From family weddings, anniversaries and milestone birthdays to reunions, private getaways and celebrations with friends, we create refined experiences around comfort, connection and unforgettable memories."/><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{EXPERIENCES.map((item,index)=><Reveal key={item.title} delay={index%3*.06} className="h-full"><article className="group h-full overflow-hidden rounded-lg border border-jungle/10 bg-white shadow-card"><div className="aspect-[16/10] overflow-hidden"><img src={item.image} alt={item.title} loading="lazy" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/></div><div className="p-6"><h2 className="font-serif text-2xl text-jungle">{item.title}</h2><p className="mt-3 text-sm leading-6 text-jungle-muted">{item.text}</p></div></article></Reveal>)}</div></div></section>
  <section className="bg-jungle-deep py-16 text-center"><blockquote className="mx-auto max-w-3xl px-6 font-serif text-2xl font-light leading-relaxed text-ivory sm:text-3xl">The finest journeys are shared with the people who matter most—creating timeless memories to cherish for generations.</blockquote></section>
  <section className="bg-sand py-20 lg:py-24"><div className="mx-auto grid max-w-content gap-12 px-6 lg:grid-cols-[.75fr_1.25fr] lg:gap-16"><SectionHeading eyebrow="Private Journey Enquiries" title="Connect With Us" subtitle="Tell us about your occasion, guests and preferred experiences. Our specialists will create a private journey shaped around the people you love." align="left"/><GroupTourInquiryForm source="family-escapes-private-celebrations" typeLabel="Celebration / Journey Type" typeOptions={['Family Holiday','Family Wedding','Anniversary','Birthday Celebration','Family Reunion','Private Getaway','Honeymoon Group','Maldives Extension','Other']} interestLabel="Preferred Experience" interestOptions={['Beach','Hill Country','Wildlife','Private Villa','Luxury Resort','Multi-Destination','Maldives Extension']} submitLabel="Plan Our Celebration"/></div></section>
  <CtaStrip eyebrow="Celebrate Together" title="Create a journey worth remembering" description="Share your occasion with us and we will create a private journey designed around the people who matter most." primaryLabel="Start Planning" primaryTo="/plan-your-trip"/>
  </>}
