import Link from 'next/link';
import { ArrowRightIcon, AwardIcon, ExternalLinkIcon, Globe2Icon, StarIcon, TrophyIcon } from 'lucide-react';
import { PageHero } from '../components/ui/PageHero';
import { Reveal } from '../components/ui/Reveal';
import { SectionHeading } from '../components/ui/SectionHeading';
import { IMAGES } from '../data/media';

type Accolade = { title: string; source: string; description: string; href: string; tag: string };

const accolades: Record<string, Accolade[]> = {
  '2026': [
    { title: 'Top 10 Happiest Travel Destinations', source: 'G Adventures Happiness List', description: 'Recognised for meaningful, community-driven and enriching travel experiences.', href: 'https://www.travelmonitor.com.au/g-adventures-releases-happiness-list-2026-as-travellers-prioritise-emotional-fulfilment/', tag: 'Meaningful Travel' },
    { title: 'Best Places to Visit in Asia', source: 'U.S. News & World Report', description: 'Celebrated for its heritage cities, tropical beaches, scenic hill country and wildlife-rich national parks.', href: 'https://travel.usnews.com/rankings/best-asian-vacations/', tag: 'Asia' },
    { title: '50 Best Places to Travel', source: 'Travel + Leisure', description: 'Featured for culture, highland hiking, coastal adventures, wildlife and its strength as a stand-alone destination.', href: 'https://www.travelandleisure.com/best-places-to-go-2026-11840319', tag: 'Editors’ Pick' },
  ],
  '2025': [
    { title: 'Global Responsible Tourism Awards', source: 'International Centre for Responsible Tourism', description: 'Sri Lankan organisations including Heritance Kandalama, Heel Oya CBT Village and Jetwing Vil Uyana received recognition.', href: 'https://icrt.global/2025-global-responsible-tourism-awards-finalists/', tag: 'Responsible Tourism' },
    { title: 'Top Destination for October', source: 'Time Out', description: 'Highlighted for shoulder-season appeal, warm weather, fewer crowds and abundant adventure.', href: 'https://www.timeout.com/travel/best-places-to-travel-in-october', tag: 'Seasonal Pick' },
    { title: 'Best Places to Travel in August', source: 'Lonely Planet', description: 'Sri Lanka’s northeast was spotlighted for Arugam Bay surf, Nilaveli, Passikudah and the Kandy Esala Perahera.', href: 'https://www.lonelyplanet.com/articles/where-to-go-in-august', tag: 'Northeast Coast' },
    { title: '7th Best Food Destination in the World', source: 'Condé Nast Traveller Readers’ Choice Awards', description: 'Sri Lanka earned a 95.56 score and a place among the world’s most celebrated culinary destinations.', href: 'https://www.cntraveller.com/gallery/best-countries-for-food', tag: 'Food' },
    { title: '50 Best Islands in the World', source: 'Big 7 Travel', description: 'Featured among the world’s standout islands for natural beauty, culture and variety.', href: 'https://www.enjoytravel.com/en/travel-news/guides/best-islands-in-the-world', tag: 'Island Life' },
    { title: 'Most Family-Friendly Country', source: 'Condé Nast Traveller', description: 'Celebrated for warm hospitality and varied family experiences, from wildlife and beaches to Galle Fort.', href: 'https://www.cntraveller.com/article/worlds-most-family-friendly-countries-2025', tag: 'Family Travel' },
    { title: '25 Best Places to Travel — No. 9', source: 'BBC Travel', description: 'Recognised for extraordinary diversity across beaches, mountains, jungles, wildlife and ancient cities.', href: 'https://www.bbc.com/travel/article/20250115-the-25-best-places-to-travel-in-2025', tag: 'Global Top 10' },
    { title: 'The Pekoe Trail — World’s Greatest Places', source: 'TIME', description: 'The 300-kilometre highland walking trail was selected for TIME’s World’s Greatest Places of 2025.', href: 'https://time.com/collections/worlds-greatest-places-2025/7263135/the-pekoe-trail/', tag: 'Highland Adventure' },
    { title: 'Kandy to Ella Scenic Train Journey', source: 'National Geographic', description: 'Sri Lanka’s iconic hill-country railway was featured as one of the world’s most breathtaking train experiences.', href: 'https://www.nationalgeographic.com/travel/article/sri-lankas-famed-kandy-to-ella-train-line', tag: 'Rail Journey' },
  ],
  '2024': [
    { title: 'Best International Tourism Board', source: 'Global Tourism Awards', description: 'The Sri Lanka Tourism Promotion Bureau received the accolade at the Global Tourism Awards in New Delhi.', href: 'https://srilanka.travel/travel-news&news=960&section=travel', tag: 'Tourism Leadership' },
    { title: 'World’s Most Desirable Island — Gold', source: 'Wanderlust Reader Travel Awards', description: 'Sri Lanka rose from eighth place in 2023 to take Gold after more than 168,000 readers cast over three million votes.', href: 'https://www.wanderlustmagazine.com/inspiration/wanderlust-travel-awards-2024-the-results/', tag: 'Readers’ Choice' },
  ],
};

const featured = [
  { year: '2024', value: 'Gold', title: 'World’s Most Desirable Island', source: 'Wanderlust Reader Travel Awards' },
  { year: '2025', value: 'Top 10', title: 'Best Places to Travel', source: 'BBC Travel' },
  { year: '2026', value: 'Top 50', title: 'Best Places to Travel', source: 'Travel + Leisure' },
];

export function GlobalAccolades() {
  return <>
    <PageHero eyebrow="Why Visit Sri Lanka" title="Global Accolades" subtitle="From the world’s most desirable island to celebrated food, family adventures and responsible tourism — Sri Lanka continues to earn global recognition." image={IMAGES.teaCountry} imageAlt="Sri Lanka's celebrated tea country and green highland landscape" locationTag="Award-Winning Sri Lanka" stats={[{ value: '14', label: 'Recent Accolades' }, { value: '2024–26', label: 'Recognition' }, { value: 'Global', label: 'Travel Authorities' }]}>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#accolades" className="rounded-full bg-gold px-8 py-4 text-xs font-semibold uppercase tracking-[.16em] text-jungle-deep">Explore the Awards</a><Link href="/plan-your-trip" className="rounded-full border border-ivory/35 bg-white/10 px-8 py-4 text-xs font-medium uppercase tracking-[.16em] text-ivory">Experience Sri Lanka</Link></div>
    </PageHero>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto grid max-w-content gap-12 px-6 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><Reveal><div><p className="eyebrow text-gold-dark">Internationally Celebrated</p><h2 className="mt-4 font-serif text-4xl font-light leading-tight text-jungle sm:text-5xl">An island the world keeps talking about</h2></div></Reveal><Reveal delay={.08}><div className="space-y-5 text-[15px] leading-8 text-jungle-muted sm:text-base"><p>Sri Lanka is more than a destination. Year after year, respected travel publications, industry organisations and reader communities recognise the island for its culture, landscapes, wildlife, food and unforgettable journeys.</p><p>These honours celebrate what travellers discover for themselves: an extraordinary variety of experiences within one compact island, shared with genuine warmth and hospitality.</p><p className="font-serif text-2xl italic text-jungle">Travel with Magical Paradise and step into one of the world’s most acclaimed destinations.</p></div></Reveal></div></section>

    <section className="bg-jungle py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Featured Recognition" title="Sri Lanka on the World Stage" tone="light"/><div className="mt-12 grid gap-5 lg:grid-cols-3">{featured.map((x,i)=><Reveal key={x.title+x.year} delay={i*.06}><article className="h-full rounded-xl border border-ivory/15 p-8"><div className="flex items-center justify-between"><TrophyIcon className="h-7 w-7 text-gold-light"/><span className="text-xs font-semibold uppercase tracking-[.16em] text-ivory/50">{x.year}</span></div><p className="mt-8 font-serif text-5xl text-gold-light">{x.value}</p><h3 className="mt-4 font-serif text-2xl text-ivory">{x.title}</h3><p className="mt-3 text-xs uppercase tracking-[.12em] text-ivory/55">{x.source}</p></article></Reveal>)}</div></div></section>

    <section id="accolades" className="scroll-mt-24 bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="2024 to Present" title="Recent Global Endorsements" subtitle="Explore the awards, rankings and editorial selections that continue to place Sri Lanka among the world’s most rewarding destinations."/>
      <div className="mt-16 space-y-20">{Object.entries(accolades).map(([year,items])=><div key={year} className="grid gap-8 lg:grid-cols-[180px_1fr]"><Reveal><div className="lg:sticky lg:top-36"><p className="font-serif text-6xl font-light text-gold sm:text-7xl">{year}</p><div className="mt-4 h-px w-20 bg-gold/50"/><p className="mt-4 text-xs uppercase tracking-[.16em] text-jungle-muted">{items.length} recognitions</p></div></Reveal><div className="grid gap-5 md:grid-cols-2">{items.map((x,i)=><Reveal key={x.title} delay={(i%2)*.05}><article className="group flex h-full flex-col rounded-xl border border-jungle/10 bg-ivory p-7 shadow-card transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between gap-4"><span className="rounded-full bg-gold/15 px-3 py-2 text-[9px] font-semibold uppercase tracking-[.14em] text-gold-dark">{x.tag}</span><AwardIcon className="h-5 w-5 shrink-0 text-gold-dark" strokeWidth={1.5}/></div><h3 className="mt-6 font-serif text-2xl leading-tight text-jungle">{x.title}</h3><p className="mt-3 text-[11px] font-semibold uppercase tracking-[.12em] text-jungle-muted">{x.source}</p><p className="mt-5 text-sm leading-7 text-jungle-muted">{x.description}</p><a href={x.href} target="_blank" rel="noreferrer noopener" className="mt-auto inline-flex items-center gap-2 pt-7 text-[10px] font-semibold uppercase tracking-[.14em] text-gold-dark">View recognition <ExternalLinkIcon className="h-3.5 w-3.5"/></a></article></Reveal>)}</div></div>)}</div>
    </div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><div className="grid gap-10 lg:grid-cols-3"><Reveal><div><Globe2Icon className="h-8 w-8 text-gold-dark"/><h3 className="mt-5 font-serif text-3xl text-jungle">One island, extraordinary variety</h3><p className="mt-4 text-sm leading-7 text-jungle-muted">Ancient cities, tea country, wildlife, surf beaches and tropical coastlines can all be woven into one journey.</p></div></Reveal><Reveal delay={.05}><div><StarIcon className="h-8 w-8 text-gold-dark"/><h3 className="mt-5 font-serif text-3xl text-jungle">Recognised by travellers</h3><p className="mt-4 text-sm leading-7 text-jungle-muted">Reader-voted awards reflect the experiences and memories of people who have explored Sri Lanka firsthand.</p></div></Reveal><Reveal delay={.1}><div><AwardIcon className="h-8 w-8 text-gold-dark"/><h3 className="mt-5 font-serif text-3xl text-jungle">A future built responsibly</h3><p className="mt-4 text-sm leading-7 text-jungle-muted">Recognition for community tourism and nature-conscious hospitality points toward more meaningful ways to travel.</p></div></Reveal></div></div></section>

    <section className="bg-jungle-deep py-20"><div className="mx-auto max-w-4xl px-6 text-center"><Reveal><p className="eyebrow text-gold-light">Discover It for Yourself</p><h2 className="mt-4 font-serif text-4xl text-ivory sm:text-5xl">Experience award-winning Sri Lanka</h2><p className="mx-auto mt-6 max-w-2xl text-[15px] leading-8 text-ivory/70">Let us craft a journey through the landscapes, flavours, heritage and wildlife that continue to capture the world’s imagination.</p><Link href="/plan-your-trip" className="mt-9 inline-flex items-center gap-2 rounded-full bg-gold px-8 py-4 text-xs font-semibold uppercase tracking-[.16em] text-jungle-deep">Plan Your Journey <ArrowRightIcon className="h-4 w-4"/></Link></Reveal></div></section>
  </>;
}
