import React from 'react';
import {PageHero} from '../components/ui/PageHero';
import {Reveal} from '../components/ui/Reveal';
import {SectionHeading} from '../components/ui/SectionHeading';
import {CtaStrip} from '../components/sections/CtaStrip';
import {GroupTourInquiryForm} from '../components/forms/GroupTourInquiryForm';
import {IMAGES} from '../data/media';

const TYPES=[['Adventure Groups','Waterfall expeditions, hiking, camping, Knuckles adventures, Ella trails, rafting and off-the-beaten-path experiences.'],['Wildlife & Safari Groups','Leopard safaris, birdwatching, elephant experiences, whale watching and photography-focused journeys.'],['Wellness & Retreat Groups','Yoga retreats, wellness escapes, Ayurveda experiences, meditation programs and slow travel concepts.'],['Golf Tours','Premium golf experiences across Colombo, Digana, Nuwara Eliya and Hambantota.'],['Photography & Nature Tours','Sunrise trails, cultural and wildlife photography, waterfalls, tea plantations and hidden landscapes.'],['Cultural & Heritage Tours','Temples, ancient kingdoms, UNESCO sites, local traditions, village experiences and authentic Sri Lankan cuisine.'],['Corporate & Incentive Travel','Team outings, MICE programs, incentive tours, executive retreats and company adventures.'],['Private Social Groups','Family reunions, birthday trips, friend circles, honeymoon groups and customized celebrations.']];
const WHY=['Shared memories and new friendships','Cost-effective luxury experiences','Safer and smoother travel planning','Access to unique local experiences','Hassle-free logistics and transportation','Dedicated tour coordinators and guides','Fun-filled journeys with like-minded travellers'];
const HANDLE=['Airport transfers','Luxury and standard accommodation','Transportation with experienced chauffeurs','Experienced local guides','Entrance tickets and activity coordination','Safari jeeps and adventure arrangements','Meal planning','Train ticket arrangements','Beach stays and wellness add-ons','Photography stops and hidden gems','Custom itineraries for different travel styles'];
const GROUPS=['Groups of friends','Families','Solo travellers joining fixed departures','Corporate teams','Photography clubs','Wellness communities','Special-interest groups','Fitness groups'];

export function GuidedGroupTours(){return <>
  <PageHero eyebrow="Travel Together" title="Guided Group Tours" subtitle="Travel Together. Explore Deeper. Experience More." image={IMAGES.ella} imageAlt="A guided group journey through Sri Lanka's hill country"/>
  <section className="bg-ivory py-20 lg:py-24"><div className="mx-auto max-w-content px-6"><div className="grid gap-12 lg:grid-cols-[1.2fr_.8fr] lg:gap-16"><div><SectionHeading eyebrow="Shared Journeys" title="Sri Lanka, experienced together" subtitle="Magical Paradise creates seamless group journeys filled with adventure, culture, nature and authentic local moments—carefully planned around comfort, safety and memorable shared experiences." align="left"/><div className="mt-7 flex flex-wrap gap-2">{GROUPS.map(item=><span key={item} className="rounded-full border border-jungle/10 bg-white px-4 py-2 text-xs text-jungle-muted">{item}</span>)}</div></div><Reveal><div className="rounded-lg bg-jungle p-8 text-ivory"><p className="eyebrow text-gold-light">Minimum Number of Participants</p><p className="mt-5 font-serif text-4xl text-gold-light">10</p><p className="mt-3 text-sm leading-6 text-ivory/70">Guided group tours operate with a minimum of 10 participants to ensure a well-organized and enjoyable experience for everyone.</p></div></Reveal></div></div></section>
  <section className="bg-sand py-20 lg:py-24"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Designed Around Your Group" title="Types of Group Tours We Organize"/><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{TYPES.map(([title,text],index)=><Reveal key={title} delay={index%4*.05} className="h-full"><article className="h-full rounded-lg border border-jungle/10 bg-ivory p-7"><span className="font-serif text-2xl text-gold-dark">0{index+1}</span><h3 className="mt-4 font-serif text-xl text-jungle">{title}</h3><p className="mt-3 text-sm leading-6 text-jungle-muted">{text}</p></article></Reveal>)}</div></div></section>
  <section className="bg-ivory py-20 lg:py-24"><div className="mx-auto grid max-w-content gap-12 px-6 lg:grid-cols-2 lg:gap-16"><div><SectionHeading eyebrow="Better Together" title="Why Travel Sri Lanka in a Group?" align="left"/><List items={WHY}/></div><div><SectionHeading eyebrow="End-to-End Planning" title="What We Handle for You" align="left"/><List items={HANDLE}/></div></div></section>
  <section className="bg-jungle-deep py-16 text-center"><blockquote className="mx-auto max-w-3xl px-6 font-serif text-2xl font-light leading-relaxed text-ivory sm:text-3xl">“More than just a tour—we create shared journeys filled with stories, friendships, adventure and unforgettable Sri Lankan moments.”</blockquote></section>
  <section className="bg-sand py-20 lg:py-24"><div className="mx-auto grid max-w-content gap-12 px-6 lg:grid-cols-[.75fr_1.25fr] lg:gap-16"><SectionHeading eyebrow="Group Enquiries" title="Connect With Us" subtitle="Tell us about your group, travel dates and the experiences you are looking for. Our specialists will help create the right journey for your group." align="left"/><GroupTourInquiryForm source="guided-group-tours" typeLabel="Group Type" typeOptions={['Friends','Family','Fixed Departure / Solo Traveller','Corporate Team','Photography Group','Wellness Group','Special Interest Group','Fitness Group','Other']} interestLabel="Tour Interests" interestOptions={['Adventure','Wildlife & Safari','Wellness','Golf','Photography & Nature','Culture & Heritage','Corporate / Incentive','Private Social Group']} submitLabel="Plan Our Group Journey"/></div></section>
  <CtaStrip eyebrow="Travel Together" title="Start planning your group journey" description="Tell us who is travelling and what inspires your group, and our specialists will shape a seamless Sri Lankan journey around you." primaryLabel="Plan Your Group Tour" primaryTo="/plan-your-trip"/>
  </>}
function List({items}:{items:string[]}){return <ul className="mt-8 grid gap-3 sm:grid-cols-2">{items.map(item=><li key={item} className="flex gap-3 rounded-lg border border-jungle/10 bg-white p-4 text-sm leading-6 text-jungle-muted"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-gold"/>{item}</li>)}</ul>}
