import Link from 'next/link';
import Image from 'next/image';
import {
  BadgeInfoIcon, BanknoteIcon, BusIcon, CheckIcon, CloudSunIcon, HeartPulseIcon,
  LandmarkIcon, LanguagesIcon, LuggageIcon, PalmtreeIcon,
  PlaneIcon, PlugIcon, ShieldCheckIcon, ShoppingBagIcon, SmartphoneIcon,
  SparklesIcon, TrainIcon, UtensilsIcon, WavesIcon,
} from 'lucide-react';
import { PageHero } from '../components/ui/PageHero';
import { Reveal } from '../components/ui/Reveal';
import { SectionHeading } from '../components/ui/SectionHeading';
import { IMAGES } from '../data/media';
import { SITE } from '../data/site';

const quickFacts = [
  { icon: PassportIcon, title: 'Passport', text: 'Your passport should be valid for at least six months from the visa application date.' },
  { icon: PlaneIcon, title: 'Main Airport', text: 'Bandaranaike International Airport (CMB) is about 35 km north of Colombo and 6 km from Negombo.' },
  { icon: CloudSunIcon, title: 'Time Zone', text: 'Sri Lanka Standard Time is GMT/UTC +5 hours 30 minutes.' },
];

function PassportIcon(props: React.ComponentProps<typeof BadgeInfoIcon>) {
  return <BadgeInfoIcon {...props} />;
}

const festivals = [
  ['Mid January', 'Thai Pongal'], ['4 February', 'Independence Day'],
  ['Late February / Early March', 'Maha Shivaratri'], ['13–14 April', 'Sinhala & Tamil New Year'],
  ['April / May', 'Good Friday & Easter'], ['May', 'Vesak Festival'],
  ['June', 'Poson Festival'], ['August', 'Kandy Esala Perahera'],
  ['October / November', 'Deepavali'], ['25 December', 'Christmas Day'],
];

const packing = ['Light cotton or linen clothing', 'Beachwear and sunglasses', 'Comfortable shoes or sandals', 'Rain jacket', 'Activewear', 'A light jumper', 'Warm layer for the hill country', 'Sunscreen and insect repellent', 'Camera', 'Modest temple clothing'];
const phrases = [['Ayubowan', 'May you live long / Hello'], ['Istuti', 'Thank you'], ['Koheda?', 'Where?'], ['Kohomada?', 'How are you?'], ['Hondai', 'Good'], ['Lassanai', 'Beautiful'], ['Sama wenna', 'Sorry / Excuse me'], ['Machan', 'Buddy / Mate']];
const emergencies = [['1912', 'Tourist Police Assistance'], ['011 242 1052', 'Tourist Police headquarters'], ['119 / 118', 'Police emergency'], ['110', 'Ambulance, fire and rescue'], ['1990', 'Free Suwa Seriya ambulance']];
const hospitals = ['National Hospital of Sri Lanka — Colombo', 'Teaching Hospital Karapitiya — Galle', 'National Hospital — Kandy', 'Asiri Central Hospital — Colombo 10', 'Lanka Hospitals — Colombo 05', 'Durdans Hospital — Colombo 03', 'Nawaloka Hospital — Colombo 02', 'Asiri Hospitals — Matara, Galle & Kandy', 'Ruhuna Hospital — Galle'];
const shopping = [['Nuwara Eliya', 'Ceylon tea'], ['Kandy', 'Gemstones, jewellery, handicrafts, sarees, sarongs and Dumbara crafts'], ['Matale', 'Authentic spices'], ['Colombo', 'Porcelain, handicrafts, antiques, handloom, malls and street food'], ['Galle', 'Moonstone carvings and traditional masks'], ['Island-wide', 'Wellness products including Spa Ceylon']];

const Card = ({ title, children }: { title: string; children: React.ReactNode }) => <article className="h-full rounded-xl border border-jungle/10 bg-white p-7 shadow-card"><h3 className="font-serif text-2xl text-jungle">{title}</h3><div className="mt-4 text-sm leading-7 text-jungle-muted">{children}</div></article>;
const Bullets = ({ items }: { items: string[] }) => <ul className="space-y-3">{items.map(x => <li key={x} className="flex gap-3"><CheckIcon className="mt-1 h-4 w-4 shrink-0 text-gold-dark" />{x}</li>)}</ul>;

export function HandyTravelAdvice() {
  return <>
    <PageHero eyebrow="Sri Lanka Travel Guide" title="Handy Travel Advice" subtitle="Practical local guidance to help you arrive prepared, travel comfortably and experience Sri Lanka with confidence." image={IMAGES.ella} imageAlt="A scenic train travelling through Sri Lanka's hill country" locationTag="Travel Essentials" stats={[{ value: '+5:30', label: 'GMT / UTC' }, { value: '230V', label: 'Power Supply' }, { value: '1990', label: 'Ambulance' }]}>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#essentials" className="rounded-full bg-gold px-8 py-4 text-xs font-semibold uppercase tracking-[.16em] text-jungle-deep">Start with Essentials</a><Link href="/plan-your-trip" className="rounded-full border border-ivory/35 bg-white/10 px-8 py-4 text-xs font-medium uppercase tracking-[.16em] text-ivory">Plan Your Trip</Link></div>
    </PageHero>

    <section id="essentials" className="scroll-mt-24 bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Before You Fly" title="Entry & Arrival Essentials" subtitle="A few simple checks before departure will make your arrival much smoother."/><div className="mt-12 grid gap-5 md:grid-cols-3">{quickFacts.map((x,i)=><Reveal key={x.title} delay={i*.05}><Card title={x.title}><x.icon className="mb-5 h-7 w-7 text-gold-dark" strokeWidth={1.5}/><p>{x.text}</p></Card></Reveal>)}</div>
      <Reveal className="mt-8"><article className="overflow-hidden rounded-xl border border-jungle/10 bg-white shadow-card"><div className="grid lg:grid-cols-[.8fr_1.2fr] lg:items-stretch"><div className="p-7 sm:p-9 lg:flex lg:flex-col lg:justify-center"><PlugIcon className="h-8 w-8 text-gold-dark" strokeWidth={1.5}/><p className="eyebrow mt-6 text-gold-dark">Travel Adapter Guide</p><h3 className="mt-3 font-serif text-3xl text-jungle">Power & Electric Sockets</h3><p className="mt-5 text-sm leading-7 text-jungle-muted">Sri Lanka uses two common socket styles: round three-pin and square three-pin wall sockets, supplied at 230V. Because fittings can vary between properties, carrying a universal travel adapter is recommended.</p></div><div className="grid gap-px bg-jungle/10 sm:grid-cols-2"><figure className="flex min-h-64 flex-col items-center justify-center bg-sand p-6"><div className="relative h-48 w-full"><Image src="/images/travel-guide/sri-lanka-square-socket.jpg" alt="Square three-pin electrical socket commonly used in Sri Lanka" fill sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" className="object-contain"/></div><figcaption className="mt-4 text-[10px] font-semibold uppercase tracking-[.14em] text-jungle-muted">Square three-pin socket</figcaption></figure><figure className="flex min-h-64 flex-col items-center justify-center bg-sand p-6"><div className="relative h-48 w-full"><Image src="/images/travel-guide/sri-lanka-round-socket.jpg" alt="Round three-pin electrical socket commonly used in Sri Lanka" fill sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" className="object-contain"/></div><figcaption className="mt-4 text-[10px] font-semibold uppercase tracking-[.14em] text-jungle-muted">Round three-pin socket</figcaption></figure></div></div></article></Reveal>
      <div className="mt-12 grid gap-6 lg:grid-cols-2"><Reveal><Card title="Visa Information"><p>A Visit Visa is an entry permit issued by the Sri Lankan Government and records the permitted period and conditions of stay.</p><p className="mt-4"><strong className="text-jungle">Tourist Visa:</strong> for holidays, sightseeing, visiting friends and relatives, medical treatment, arts or sporting events.</p><p className="mt-4"><strong className="text-jungle">Business Visa:</strong> for short business visits, with entry conditions based on the approved visa.</p><a className="mt-6 inline-flex text-xs font-semibold uppercase tracking-wider text-gold-dark underline underline-offset-4" href="https://eta.gov.lk/slvisa/" target="_blank" rel="noreferrer noopener">Sri Lanka ETA Portal</a></Card></Reveal><Reveal delay={.06}><Card title="Immigration Contact"><p>Department of Immigration and Emigration<br/>Ananda Rajakaruna Mawatha, Maradana, Colombo 10</p><p className="mt-4">Tel: +94 11 532 9000 / +94 11 532 9316</p><a className="mt-5 inline-flex text-xs font-semibold uppercase tracking-wider text-gold-dark underline underline-offset-4" href="https://www.immigration.gov.lk/" target="_blank" rel="noreferrer noopener">Official Immigration Website</a><p className="mt-5 border-t border-jungle/10 pt-5 text-xs">Visa-free programmes can change. Confirm current requirements with the ETA portal or your tour coordinator before travel.</p></Card></Reveal></div>
    </div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="At the Airport" title="Arrival, Fast Track & Connectivity"/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Reveal><Card title="Bandaranaike International Airport"><p>Travel time is usually about one hour to central Colombo. The Southern Expressway connects the airport to the south coast, generally within two to three hours depending on traffic and destination.</p></Card></Reveal><Reveal delay={.05}><Card title="BIA Silk Route"><p>A premium arrival and departure service with dedicated check-in, fast-track immigration and security, personal assistance, lounge access and baggage handling.</p><a className="mt-5 inline-flex text-xs font-semibold uppercase tracking-wider text-gold-dark underline underline-offset-4" href="https://www.airport.lk/fast_track/silk_route" target="_blank" rel="noreferrer noopener">Silk Route Details</a></Card></Reveal><Reveal delay={.1}><Card title="SIM Cards & Wi-Fi"><SmartphoneIcon className="mb-4 h-7 w-7 text-gold-dark"/><p>Airport SIM cards are convenient when hotel Wi-Fi is not strong enough. Dialog and Mobitel are widely used service providers.</p></Card></Reveal></div>
      <Reveal className="mt-8"><div className="rounded-xl bg-jungle p-7 text-ivory sm:p-9"><h3 className="font-serif text-2xl text-gold-light">Customs & Duty-Free Allowances</h3><div className="mt-5 grid gap-4 text-sm leading-7 text-ivory/75 md:grid-cols-3"><p>Declare foreign currency exceeding the equivalent of USD 10,000 on arrival.</p><p>Declare valuable equipment, jewellery and gems if you intend to take them out again.</p><p>Goods in commercial or bulk quantities are not permitted as personal baggage.</p></div></div></Reveal>
    </div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Sunshine Somewhere" title="Weather & Best Time to Visit" subtitle="Sri Lanka is a year-round destination because its two monsoons affect different regions at different times."/><div className="mt-12 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Reveal><Card title="Climate at a Glance"><p>Coastal areas and Colombo commonly sit around 28–35°C, while the hill country is cooler; Nuwara Eliya averages around 16°C. Weather never runs exactly to schedule, so a short shower can appear in a dry spell and blue skies can arrive in the rainy season.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{['First inter-monsoon · March–April','Southwest monsoon · May–September','Second inter-monsoon · October–November','Northeast monsoon · December–February'].map(x=><p key={x} className="rounded-lg bg-sand px-4 py-3 text-xs text-jungle">{x}</p>)}</div></Card></Reveal><Reveal delay={.06}><Card title="Beach & Wildlife"><WavesIcon className="mb-4 h-7 w-7 text-gold-dark"/><p>December to April usually brings the most reliable beach weather. Yala is often best for leopard sightings from December to March, while Minneriya’s elephant gathering usually peaks from August to September.</p></Card></Reveal></div></div></section>

    <section className="bg-jungle py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Plan Around the Calendar" title="Festivals & Busy Travel Months" tone="light"/><div className="mt-12 grid gap-x-10 gap-y-3 sm:grid-cols-2 lg:grid-cols-3">{festivals.map(([date,name])=><Reveal key={name}><div className="flex items-baseline justify-between gap-4 border-b border-ivory/15 py-4"><span className="font-serif text-lg text-ivory">{name}</span><span className="text-right text-[10px] uppercase tracking-wider text-gold-light">{date}</span></div></Reveal>)}</div><p className="mx-auto mt-10 max-w-3xl text-center text-sm leading-7 text-ivory/70">January, April, August and December are especially busy for hotels. Book early if you have a particular property in mind or are travelling for a celebration.</p></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Pack Smart" title="What to Wear & Bring"/><div className="mt-12 grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><Reveal><Card title="Packing Checklist"><Bullets items={packing}/></Card></Reveal><div className="grid gap-6"><Reveal delay={.05}><Card title="Hotels & Laundry"><p>Standard check-in is generally 2:00 PM and check-out is 12:00 noon, subject to each property. Early check-in depends on availability. Laundry is available in most four- and five-star hotels, with laundromats in larger towns.</p></Card></Reveal><Reveal delay={.1}><Card title="Mosquitoes, Insects & Leeches"><p>Carry insect repellent in this tropical climate. Harmless leeches can occur on wet hill-country trails; leech socks are useful for hikes and rainy conditions.</p></Card></Reveal></div></div></div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Respectful Travel" title="Temples, Photography & Local Customs"/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Reveal><Card title="Temple Etiquette"><LandmarkIcon className="mb-4 h-7 w-7 text-gold-dark"/><p>Cover shoulders and knees, remove shoes and head coverings, and dress modestly. Ask permission before photographing people or sacred interiors.</p></Card></Reveal><Reveal delay={.05}><Card title="Buddha Images"><p>Never pose with your back to a Buddha statue or take selfies that may be considered disrespectful. Cover visible Buddha tattoos in public places.</p></Card></Reveal><Reveal delay={.1}><Card title="Photography"><p>Follow posted restrictions at historic, cultural and religious sites. Some places limit photography for conservation, copyright or sacred reasons.</p></Card></Reveal></div></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Travelling Together" title="Families & Children"/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Reveal><Card title="Car Seats"><p>Tell us in advance if you need a child seat, especially for toddlers. Locally available sizes and fittings may differ from what your child normally uses.</p></Card></Reveal><Reveal delay={.05}><Card title="Seat Belts & Vehicles"><p>A private van can offer families more space. Many vans and buses have lap belts in rear seats, so child-seat compatibility needs to be checked beforehand.</p></Card></Reveal><Reveal delay={.1}><Card title="Meals for Kids"><p>Request non-spicy food clearly and ask about preparation time before ordering. Keeping a familiar snack handy can make longer waits easier.</p></Card></Reveal></div></div></section>

    <section className="bg-jungle-deep py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Stay Well" title="Health, Water & Safety" tone="light"/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Reveal><div className="h-full rounded-xl border border-ivory/15 p-7"><HeartPulseIcon className="h-7 w-7 text-gold-light"/><h3 className="mt-5 font-serif text-2xl text-ivory">Health Care</h3><p className="mt-4 text-sm leading-7 text-ivory/70">Public and private hospitals are available; private hospitals often offer quicker appointments. Many five-star hotels can arrange emergency medical help.</p></div></Reveal><Reveal delay={.05}><div className="h-full rounded-xl border border-ivory/15 p-7"><ShieldCheckIcon className="h-7 w-7 text-gold-light"/><h3 className="mt-5 font-serif text-2xl text-ivory">Everyday Safety</h3><p className="mt-4 text-sm leading-7 text-ivory/70">Sri Lanka is generally safe, but use normal travel precautions. Avoid close contact with stray or wild animals and limit solo late-night outings in unfamiliar areas.</p></div></Reveal><Reveal delay={.1}><div className="h-full rounded-xl border border-ivory/15 p-7"><PalmtreeIcon className="h-7 w-7 text-gold-light"/><h3 className="mt-5 font-serif text-2xl text-ivory">Drinking Water</h3><p className="mt-4 text-sm leading-7 text-ivory/70">Do not drink tap water unless it is specifically confirmed safe. Choose sealed bottled water or properly filtered water.</p></div></Reveal></div>
      <div className="mt-12 grid gap-10 lg:grid-cols-2"><div><h3 className="font-serif text-2xl text-gold-light">Emergency Numbers</h3><dl className="mt-5 space-y-3">{emergencies.map(([n,x])=><div key={n} className="flex justify-between gap-4 border-b border-ivory/15 py-3"><dt className="font-semibold text-ivory">{n}</dt><dd className="text-right text-sm text-ivory/65">{x}</dd></div>)}</dl></div><div><h3 className="font-serif text-2xl text-gold-light">Major Hospitals</h3><ul className="mt-5 grid gap-3 sm:grid-cols-2">{hospitals.map(x=><li key={x} className="text-sm leading-6 text-ivory/65">{x}</li>)}</ul></div></div>
    </div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Money Matters" title="Currency, Cards, Banks & ATMs"/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Reveal><Card title="Sri Lankan Rupee"><BanknoteIcon className="mb-4 h-7 w-7 text-gold-dark"/><p>Official currency: Sri Lankan Rupees (LKR). Common notes include Rs 20, 50, 100, 500, 1,000 and 5,000; smaller cash is useful in local shops.</p></Card></Reveal><Reveal delay={.05}><Card title="Cards & Exchange"><p>Visa and Mastercard are widely accepted. Inform your bank before travel. Exchange foreign currency at airport banks, banks or authorised dealers and keep your passport available.</p></Card></Reveal><Reveal delay={.1}><Card title="Banks & ATMs"><p>Typical bank hours are 9:00 AM–3:00 PM. ATMs are common in towns but scarcer in rural areas. Poya days and official holidays are bank holidays.</p></Card></Reveal></div></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Meet Sri Lanka" title="Culture, Language & Food"/><div className="mt-12 grid gap-8 lg:grid-cols-2"><Reveal><Card title="Useful Sinhala Phrases"><LanguagesIcon className="mb-5 h-7 w-7 text-gold-dark"/><div className="grid gap-3 sm:grid-cols-2">{phrases.map(([a,b])=><div key={a} className="border-b border-jungle/10 pb-3"><p className="font-semibold uppercase tracking-wider text-[11px] text-jungle">{a}</p><p className="mt-1 text-xs">{b}</p></div>)}</div></Card></Reveal><Reveal delay={.06}><Card title="Authentic Food"><UtensilsIcon className="mb-5 h-7 w-7 text-gold-dark"/><p>Sri Lankan cooking centres on rice, coconut, spices, vegetables and seafood. Rice and curry may include dhal, chicken, fish, gotu kola sambol, coconut sambol and fruit curries.</p><p className="mt-4"><strong className="text-jungle">Food allergies:</strong> tell hotels, guides and waiters clearly. Maldive fish, cashews and mustard can appear unexpectedly. Carry essential medication, including prescribed auto-injectors, in hand luggage.</p></Card></Reveal></div><div className="mt-6 grid gap-6 lg:grid-cols-3"><Reveal><Card title="Alcohol"><p>Licensed wine stores and some supermarkets sell alcohol. Bars and shops close on Poya days.</p></Card></Reveal><Reveal delay={.04}><Card title="Smoking"><p>Smoking is permitted only in designated smoking areas.</p></Card></Reveal><Reveal delay={.08}><Card title="Tipping"><p>Not mandatory, but customary and appreciated for guides, drivers, hotel staff and restaurant service.</p></Card></Reveal></div></div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="On the Move" title="Transportation in Sri Lanka"/><div className="mt-12 grid gap-6 lg:grid-cols-2"><Reveal><Card title="Private Chauffeur-Guide"><LuggageIcon className="mb-4 h-7 w-7 text-gold-dark"/><p>The safest and most convenient choice for a tailored trip. A dedicated chauffeur offers secure luggage storage, flexible stops, local knowledge and support if plans or vehicles change.</p></Card></Reveal><Reveal delay={.05}><Card title="Tuk Tuks"><p>Fun for short journeys. Prefer metered vehicles, agree the fare before leaving, or use trusted ride-hailing apps such as PickMe or Uber where available.</p></Card></Reveal><Reveal><Card title="Buses"><BusIcon className="mb-4 h-7 w-7 text-gold-dark"/><p>Local buses are inexpensive but can be crowded, fast-moving and uncomfortable with luggage. A short ride can be an experience, but they are less suited to a relaxed itinerary.</p></Card></Reveal><Reveal delay={.05}><Card title="Scenic Trains"><TrainIcon className="mb-4 h-7 w-7 text-gold-dark"/><p>Routes through Kandy, Nuwara Eliya, Ella, Jaffna and Galle can be memorable. Hill-country tickets sell quickly and should be requested early.</p><p className="mt-4 text-xs">Tickets and adjacent seats cannot be guaranteed until Sri Lanka Railways releases and confirms them. Specific scenic-side window seats cannot be reserved.</p></Card></Reveal><Reveal><Card title="Domestic Flights"><PlaneIcon className="mb-4 h-7 w-7 text-gold-dark"/><p>Scheduled or charter flights can save time for destinations such as Trincomalee, Passikudah, Yala, Sigiriya, Kandy and seasonally Nuwara Eliya.</p></Card></Reveal><Reveal delay={.05}><Card title="Travellers with Special Needs"><p>Airport wheelchair support can be arranged. Accessibility varies around the island, so travelling with a companion and planning transport and accommodation in advance is recommended.</p></Card></Reveal></div></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Take Something Home" title="What to Shop & Where"/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{shopping.map(([place,items],i)=><Reveal key={place} delay={(i%3)*.04}><div className="h-full rounded-lg border border-jungle/10 bg-ivory p-6"><ShoppingBagIcon className="h-5 w-5 text-gold-dark"/><h3 className="mt-4 font-serif text-xl text-jungle">{place}</h3><p className="mt-2 text-sm leading-6 text-jungle-muted">{items}</p></div></Reveal>)}</div><p className="mt-10 text-center text-sm text-jungle-muted">Casinos are located in Colombo, including Bally’s, Bellagio, Ritz Club, Stardust and Casino Marina.</p></div></section>

    <section className="bg-jungle-deep py-20"><div className="mx-auto max-w-4xl px-6 text-center"><Reveal><SparklesIcon className="mx-auto h-8 w-8 text-gold-light"/><p className="eyebrow mt-6 text-gold-light">Travel With Confidence</p><h2 className="mt-4 font-serif text-4xl text-ivory sm:text-5xl">Let us take care of the details</h2><p className="mx-auto mt-6 max-w-2xl text-[15px] leading-8 text-ivory/70">From airport fast track and train reservations to family-friendly vehicles and carefully timed routes, our local team is here to make your journey effortless.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/plan-your-trip" className="rounded-full bg-gold px-8 py-4 text-xs font-semibold uppercase tracking-[.16em] text-jungle-deep">Plan Your Trip</Link><a href={SITE.whatsapp} target="_blank" rel="noreferrer noopener" className="rounded-full border border-ivory/30 px-8 py-4 text-xs font-medium uppercase tracking-[.16em] text-ivory">Ask Our Team</a></div></Reveal></div></section>
  </>;
}
