import Link from 'next/link';
import { CheckIcon, CloudSunIcon, CompassIcon, MapPinIcon, PalmtreeIcon, PlaneIcon, ShipIcon, SunIcon, WavesIcon } from 'lucide-react';
import { PageHero } from '../components/ui/PageHero';
import { Reveal } from '../components/ui/Reveal';
import { SectionHeading } from '../components/ui/SectionHeading';
import { IMAGES } from '../data/media';
import { SITE } from '../data/site';

const reasons = ['Crystal-clear turquoise waters', 'Luxury overwater villas', 'Private island experiences', 'World-famous snorkelling & diving', 'Marine life and coral reefs', 'Romantic honeymoon escapes', 'Luxury spa & wellness', 'Secluded beaches', 'Spectacular sunsets', 'Year-round tropical weather'];
const experiences = ['Snorkelling & Diving', 'Dolphin Watching', 'Sandbank Dining', 'Sunset Cruises', 'Luxury Spa Treatments', 'Water Sports', 'Private Island Excursions', 'Seaplane Transfers', 'Romantic Beach Dinners', 'Island Hopping', 'Fishing Excursions', 'Wellness Retreats'];
const transfers = [
  { icon: ShipIcon, title: 'Speedboat Transfer', best: 'Resorts close to Velana International Airport', time: '10–90 minutes', note: 'A direct and convenient option for nearby atolls.' },
  { icon: PlaneIcon, title: 'Seaplane Transfer', best: 'Luxury resorts farther from Malé', time: '20–60 minutes', note: 'Operates during daylight hours, approximately 6:00 AM–4:30 PM.' },
  { icon: CompassIcon, title: 'Domestic Flight + Speedboat', best: 'Resorts in distant atolls', time: '45–90 minute flight + 15–45 minute boat ride', note: 'The usual connection for remote islands.' },
];
const holidays = [
  { title: 'Maldives Tropical Escape', duration: '4 Nights / 5 Days', text: 'A relaxing island getaway surrounded by turquoise lagoons, white sandy beaches and endless ocean views.', highlights: ['Beautiful resort stay', 'Pristine beaches', 'Snorkelling experiences', 'Indian Ocean sunsets', 'Optional water activities'], for: 'Couples · Families · Beach Lovers' },
  { title: 'Maldives Luxury Retreat', duration: '5 Nights / 6 Days', text: 'An indulgent island experience combining luxury accommodation, breathtaking surroundings and exceptional hospitality.', highlights: ['Luxury resort experience', 'Beach or water villa', 'Spa and wellness', 'Sunset experiences', 'Private dining options'], for: 'Luxury Holidays · Honeymoons · Celebrations' },
  { title: 'Maldives Family Island Adventure', duration: '5 Nights / 6 Days', text: 'A tropical family holiday filled with fun, relaxation and unforgettable ocean experiences.', highlights: ['Family-friendly resorts', 'Snorkelling', 'Dolphin watching', 'Beach activities', 'Island exploration'], for: 'Families · Multi-generational Holidays' },
];
const combined = [
  { title: 'Sri Lanka Discovery & Maldives Escape', duration: '10 Nights / 11 Days', route: 'Colombo → Sigiriya → Kandy → Nuwara Eliya → Ella → Yala → Galle → Maldives', text: 'Cultural treasures, scenic landscapes and wildlife followed by a breathtaking island escape.', highlights: ['Sigiriya Rock Fortress', 'Temple of the Tooth', 'Hill country journey', 'Wildlife safari', 'Maldives beach stay'] },
  { title: 'Wildlife, Culture & Maldives Paradise', duration: '12 Nights / 13 Days', route: 'Negombo → Wilpattu → Cultural Triangle → Riverston → Mahiyanganaya → Haputale → Rakwana → Yala → Maldives', text: 'A perfect blend of adventure, natural beauty and peaceful island relaxation.', highlights: ['National park safari', 'Scenic train journey', 'Waterfalls and mountains', 'Local culture', 'Island relaxation'] },
  { title: 'Romantic Sri Lanka & Maldives Honeymoon', duration: '10 Nights / 11 Days', route: 'Sigiriya → Matale → Hatton → Colombo → Maldives', text: 'Sri Lanka’s romance, adventure and culture paired with Maldivian island serenity.', highlights: ['Boutique stays', 'Scenic hill country', 'Private experiences', 'Wildlife safari', 'Beach villa'] },
  { title: 'Luxury Island Duo', duration: '18 Nights / 19 Days', route: 'Negombo → Anuradhapura → Sigiriya → Kandy → Hatton → Ella → Yala → Weligama → Maldives', text: 'A carefully crafted luxury journey showcasing the finest of both island nations.', highlights: ['Luxury hotels', 'Private chauffeur-guide', 'Fine dining', 'Wildlife and culture', 'Maldives resort stay'] },
];
const resorts = ['Sun Siyam Olhuveli', 'Siyam World', 'Sun Siyam Iru Fushi', 'Sun Siyam Iru Veli', 'Oaga Art Resort', 'Sheraton Maldives Full Moon Resort & Spa', 'Stone Hotels Dhiffushi', 'Hard Rock Hotel Maldives', 'Machchafushi Island Resort & Spa Maldives', 'Villa Nautica Paradise Island', 'Centara Mirage Lagoon Maldives', 'Cinnamon Velifushi Maldives', 'Cinnamon Hakuraa Huraa Maldives', 'Cinnamon Dhonveli Maldives', 'Ellaidhoo Maldives by Cinnamon', 'Heritance Aarah', 'Adaaran Select Meedhupparu', 'Adaaran Prestige Water Villas', 'Adaaran Prestige Vadoo'];

const TickList = ({ items }: { items: string[] }) => <ul className="mt-6 space-y-3">{items.map(x => <li key={x} className="flex gap-3 text-sm text-jungle-muted"><CheckIcon className="h-4 w-4 shrink-0 text-gold-dark" />{x}</li>)}</ul>;

export function MaldivesTours() {
  return <>
    <PageHero eyebrow="Indian Ocean Escapes" title="Maldives Tours" subtitle="Where the ocean meets eternity — turquoise lagoons, white-sand beaches and unforgettable island escapes curated around you." image={IMAGES.maldives} imageAlt="Overwater villas surrounded by a turquoise Maldivian lagoon" locationTag="Maldives" stats={[{ value: '1,190', label: 'Islands' }, { value: '26', label: 'Natural Atolls' }, { value: 'Year-round', label: 'Tropical Warmth' }]}>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#holidays" className="rounded-full bg-gold px-8 py-4 text-xs font-semibold uppercase tracking-[.16em] text-jungle-deep">Explore Holidays</a><Link href="/plan-your-trip" className="rounded-full border border-ivory/35 bg-white/10 px-8 py-4 text-xs font-medium uppercase tracking-[.16em] text-ivory">Plan Your Escape</Link></div>
    </PageHero>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto grid max-w-content gap-12 px-6 lg:grid-cols-[.85fr_1.15fr] lg:gap-20"><Reveal><div><p className="eyebrow text-gold-dark">Welcome to the Maldives</p><h2 className="mt-4 font-serif text-4xl font-light leading-tight text-jungle sm:text-5xl">Your perfect island escape, made personal</h2></div></Reveal><Reveal delay={.08}><div className="space-y-5 text-[15px] leading-8 text-jungle-muted sm:text-base"><p>Experience unmatched beauty where turquoise lagoons, white sandy beaches, luxury resorts and unforgettable tropical experiences come together.</p><p>Whether you are planning a honeymoon, family vacation, romantic getaway, diving holiday or luxury retreat, we curate a seamless journey tailored to your travel style.</p><p>From overwater villas and private-island stays to snorkelling adventures and sunset cruises, every holiday balances relaxation, romance and tropical luxury.</p></div></Reveal></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Island Highlights" title="Why Visit the Maldives?" subtitle="A rare world of serene lagoons, remarkable marine life and private island luxury."/><ul className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{reasons.map((x, i) => <li key={x}><Reveal delay={(i%5)*.04} className="h-full"><div className="flex h-full gap-3 rounded-lg border border-jungle/10 bg-ivory p-5"><CheckIcon className="h-5 w-5 shrink-0 text-gold-dark"/><span className="text-sm leading-6 text-jungle">{x}</span></div></Reveal></li>)}</ul></div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Plan With Confidence" title="Weather & Best Time to Visit"/><div className="mt-12 grid gap-6 lg:grid-cols-3">{[
      { icon: SunIcon, title: 'November to April', label: 'Best time to visit', text: 'Sunny skies, calm seas and excellent beach conditions.' },
      { icon: CloudSunIcon, title: 'May to October', label: 'Monsoon season', text: 'Tropical showers, great surfing and attractive resort offers.' },
      { icon: WavesIcon, title: '26°C to 31°C', label: 'Year-round temperatures', text: 'Warm tropical weather makes the Maldives a year-round destination.' },
    ].map((x,i)=><Reveal key={x.title} delay={i*.06}><div className="h-full rounded-xl border border-jungle/10 bg-white p-8 shadow-card"><x.icon className="h-8 w-8 text-gold-dark"/><p className="eyebrow mt-7 text-gold-dark">{x.label}</p><h3 className="mt-3 font-serif text-3xl text-jungle">{x.title}</h3><p className="mt-4 text-sm leading-7 text-jungle-muted">{x.text}</p></div></Reveal>)}</div></div></section>

    <section className="bg-jungle py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Travel Essentials" title="Things to Know Before You Go" tone="light"/><div className="mt-12 grid gap-x-12 gap-y-10 md:grid-cols-2 lg:grid-cols-3">{[
      ['Capital & Airport','Malé · Velana International Airport (MLE)'], ['Visa Information','Visa on arrival is available to many nationalities, commonly for 30 days, subject to current immigration requirements.'], ['Currency','The Maldivian Rufiyaa is local currency; US dollars and major cards are widely accepted at resorts.'], ['Culture & Customs','The Maldives is an Islamic country. Respect local customs, particularly on inhabited islands.'], ['Alcohol','Available at licensed tourist resorts and liveaboards, but restricted on public local islands.'], ['From Sri Lanka','A direct international flight from Colombo to Malé typically takes around 1 hour 30 minutes.']
    ].map(([a,b])=><Reveal key={a}><div className="border-t border-ivory/20 pt-6"><h3 className="font-serif text-xl text-gold-light">{a}</h3><p className="mt-3 text-sm leading-7 text-ivory/70">{b}</p></div></Reveal>)}</div></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Island Connections" title="Getting Around the Maldives" subtitle="Your resort location determines the transfer. We coordinate every connection."/><div className="mt-12 grid gap-6 lg:grid-cols-3">{transfers.map((x,i)=><Reveal key={x.title} delay={i*.06}><article className="h-full rounded-xl border border-jungle/10 bg-ivory p-8"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-jungle text-gold-light"><x.icon className="h-5 w-5"/></span><h3 className="mt-6 font-serif text-2xl text-jungle">{x.title}</h3><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-gold-dark">Best for</p><p className="mt-2 text-sm leading-6 text-jungle-muted">{x.best}</p><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-gold-dark">Travel time</p><p className="mt-2 text-sm text-jungle-muted">{x.time}</p><p className="mt-6 border-t border-jungle/10 pt-5 text-xs leading-6 text-jungle-muted">{x.note}</p></article></Reveal>)}</div><p className="mx-auto mt-8 max-w-4xl text-center text-xs leading-6 text-jungle-muted">Resort transfers are commonly arranged by the resort and may not be included in room rates. Arrival time matters for daylight-only seaplanes.</p></div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Make It Unforgettable" title="Experiences in the Maldives"/><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{experiences.map((x,i)=><Reveal key={x} delay={(i%4)*.035}><div className="flex min-h-28 items-end rounded-lg border border-jungle/10 bg-white p-5 shadow-card"><p className="font-serif text-lg text-jungle">{x}</p></div></Reveal>)}</div></div></section>

    <section id="holidays" className="scroll-mt-24 bg-sand py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Maldives Holidays" title="Choose Your Island Escape" subtitle="Every itinerary can be tailored to your dates, pace and preferred resort style."/><div className="mt-12 grid gap-6 lg:grid-cols-3">{holidays.map((x,i)=><Reveal key={x.title} delay={i*.06}><article className="flex h-full flex-col rounded-xl bg-ivory p-8 shadow-card ring-1 ring-jungle/10"><p className="eyebrow text-gold-dark">{x.duration}</p><h3 className="mt-4 font-serif text-3xl text-jungle">{x.title}</h3><p className="mt-5 text-sm leading-7 text-jungle-muted">{x.text}</p><TickList items={x.highlights}/><p className="mt-auto pt-8 text-xs font-medium uppercase tracking-[.1em] text-jungle">{x.for}</p></article></Reveal>)}</div></div></section>

    <section className="bg-ivory py-20 lg:py-28"><div className="mx-auto max-w-content px-6"><SectionHeading eyebrow="Two Islands, One Journey" title="Sri Lanka & Maldives Combined Tours" subtitle="Pair Sri Lanka’s culture, wildlife and landscapes with the Maldives’ effortless island luxury."/><div className="mt-12 grid gap-6 lg:grid-cols-2">{combined.map((x,i)=><Reveal key={x.title} delay={(i%2)*.06}><article className="h-full rounded-xl border border-jungle/10 bg-sand p-8"><div className="flex flex-wrap justify-between gap-3"><p className="eyebrow text-gold-dark">Tailor-made journey</p><span className="rounded-full bg-jungle px-4 py-2 text-[10px] uppercase tracking-wider text-ivory">{x.duration}</span></div><h3 className="mt-5 font-serif text-3xl text-jungle">{x.title}</h3><p className="mt-4 text-sm leading-7 text-jungle-muted">{x.text}</p><div className="mt-6 flex gap-3 border-y border-jungle/10 py-5"><MapPinIcon className="h-4 w-4 shrink-0 text-gold-dark"/><p className="text-xs leading-6 text-jungle">{x.route}</p></div><TickList items={x.highlights}/></article></Reveal>)}</div></div></section>

    <section className="bg-sand py-20 lg:py-28"><div className="mx-auto grid max-w-content gap-12 px-6 lg:grid-cols-[.75fr_1.25fr]"><Reveal><div><p className="eyebrow text-gold-dark">Where You Could Stay</p><h2 className="mt-4 font-serif text-4xl text-jungle sm:text-5xl">Maldives Resorts</h2><p className="mt-5 text-sm leading-7 text-jungle-muted">We match the right resort, room category and transfer to your travel style.</p></div></Reveal><Reveal delay={.08}><ul className="grid gap-x-8 sm:grid-cols-2">{resorts.map(x=><li key={x} className="flex gap-3 border-b border-jungle/10 py-3 text-sm text-jungle"><PalmtreeIcon className="h-4 w-4 shrink-0 text-gold-dark"/>{x}</li>)}</ul></Reveal></div></section>

    <section className="bg-jungle-deep py-20"><div className="mx-auto max-w-4xl px-6 text-center"><Reveal><p className="eyebrow text-gold-light">Your Journey, Your Way</p><h2 className="mt-4 font-serif text-4xl text-ivory sm:text-5xl">Start planning your Sri Lanka & Maldives adventure</h2><p className="mx-auto mt-6 max-w-2xl text-[15px] leading-8 text-ivory/70">Extend your beach stay, upgrade your accommodation or add unique local experiences. Our team will design the journey around you.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/plan-your-trip" className="rounded-full bg-gold px-8 py-4 text-xs font-semibold uppercase tracking-[.16em] text-jungle-deep">Plan Your Trip</Link><a href={SITE.whatsapp} target="_blank" rel="noreferrer noopener" className="rounded-full border border-ivory/30 px-8 py-4 text-xs font-medium uppercase tracking-[.16em] text-ivory">Talk to an Expert</a></div></Reveal></div></section>
  </>;
}
